#!/usr/bin/env bash

CONTROL_OPS=("||" "&&" "|&" "|" ";" "&")

is_control_op() {
    local token="$1"
    for op in "${CONTROL_OPS[@]}"; do
        [[ "$token" == "$op" ]] && return 0
    done
    return 1
}

preprocess_ops() {
    local s="$1"
    # Longest operators first to avoid splitting their components incorrectly
    s="${s//|&/ |& }"
    s="${s//||/ || }"
    s="${s//&&/ && }"
    s="${s//;/ ; }"
    s="${s//|/ | }"
    s="${s//&/ & }"
    echo "$s"
}

parse_bash_command() {
    local input
    input="$(preprocess_ops "$1")"

    local tokens=()
    read -r -a tokens <<< "$input"

    local current_cmd=()
    local commands=()
    local ops=()

    for tok in "${tokens[@]}"; do
        if is_control_op "$tok"; then
            if [[ ${#current_cmd[@]} -gt 0 ]]; then
                commands+=("$(printf "%s " "${current_cmd[@]}")")
                ops+=("$tok")
                current_cmd=()
            fi
        else
            current_cmd+=("$tok")
        fi
    done

    if [[ ${#current_cmd[@]} -gt 0 ]]; then
        commands+=("$(printf "%s " "${current_cmd[@]}")")
        ops+=("")
    fi

    echo "=== Parsed Commands ==="
    for ((i=0; i<${#commands[@]}; i++)); do
        echo "$((i+1)). Command: ${commands[$i]}"
        [[ -n "${ops[$i]}" ]] && echo "   Operator: ${ops[$i]}"
    done
}

parse() {
    if [[ -n "$1" ]]; then
        fcmd="$*"
    else
        fcmd="$(fc -ln -1)"
    fi

    parse_bash_command "$fcmd"
}


18:10:39 Thu Dec 04: ~ $ curl -s ipinfo.io | sed -n '2p'| sed 's/"/ /g'| awk '{print $3}'
185.172.52.109

18:10:42 Thu Dec 04: ~ $ parse 
=== Parsed Commands ===
1. Command: curl -s ipinfo.io 
   Operator: |
2. Command: sed -n '2p' 
   Operator: |
3. Command: sed 's/"/ /g' 
   Operator: |
4. Command: awk '{print $3}' 

18:14:57 Thu Dec 04: ~ $ parse 'ps aux | awk '$8 ~ /^[Zz]/ {print $2}' | xargs -I {} ps -o ppid= -p {} | xargs -I {} kill -9 {}'
=== Parsed Commands ===
1. Command: ps aux 
   Operator: |
2. Command: awk /home/jb /^[Zz]/ {print } 
   Operator: |
3. Command: xargs -I {} ps -o ppid= -p {} 
   Operator: |
4. Command: xargs -I {} kill -9 {} 

18:15:03 Thu Dec 04: ~ $ ip addr show | grep inet | grep -v inet6 | awk '{print $2}' | cut -d/ -f1
127.0.0.1
192.168.122.1
192.168.1.147
10.5.0.2

18:15:49 Thu Dec 04: ~ $ parse 
=== Parsed Commands ===
1. Command: ip addr show 
   Operator: |
2. Command: grep inet 
   Operator: |
3. Command: grep -v inet6 
   Operator: |
4. Command: awk '{print $2}' 
   Operator: |
5. Command: cut -d/ -f1 



18:17:52 Thu Dec 04: ~ $ parse 'apt update & apt upgrade &'
=== Parsed Commands ===
1. Command: apt update 
   Operator: &
2. Command: apt upgrade 
   Operator: &

18:26:31 Thu Dec 04: ~ $ parse 'apt update ; apt upgrade ; mkdir test'
=== Parsed Commands ===
1. Command: apt update 
   Operator: ;
2. Command: apt upgrade 
   Operator: ;
3. Command: mkdir test 

18:26:54 Thu Dec 04: ~ $ ping -c3 www.tecmint.com && links www.tecmint.com
PING www.tecmint.com (104.26.2.23) 56(84) bytes of data.
64 bytes from 104.26.2.23: icmp_seq=1 ttl=56 time=48.2 ms
64 bytes from 104.26.2.23: icmp_seq=2 ttl=56 time=86.9 ms
^C
--- www.tecmint.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 48.233/67.580/86.928/19.347 ms
bash: links: command not found

18:27:11 Thu Dec 04: ~ $ parse
=== Parsed Commands ===
1. Command: ping -c3 www.tecmint.com 
   Operator: &
2. Command: links www.tecmint.com 

18:27:17 Thu Dec 04: ~ $ mkdir test || links tecmint.com

18:28:29 Thu Dec 04: ~ $ parse
=== Parsed Commands ===
1. Command: mkdir test 
   Operator: |                            ####### oops should be ||
2. Command: links tecmint.com 

18:28:31 Thu Dec 04: ~ $ 
















